### ISSUE TITLE
 the role 'ansible-nexus' was not found 

### ISSUE THREAD

**Issue by patsevanton** [opsta/ansible-nexus#19]
Hello!
Thanks for role

I try install nexus and get error
```
ERROR! the role 'ansible-nexus' was not found in /home/user/github/infrastructure-as-a-code-example/10-nexus/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/user/github/infrastructure-as-a-code-example/10-nexus

The error appears to be in '/home/user/github/infrastructure-as-a-code-example/10-nexus/playbook.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - ansible-nexus
      ^ here

```

Install role before
```
ansible-galaxy install opsta.nexus
```

Playbook
```
---
- name: Install nexus
  hosts: nexus
  become: yes

  roles:
    - ansible-nexus
```
